var WTA;var v={};var dotImgId;var images=[];var index=0;var env = "";var prodHomeMetricsHostDomains = new Array("home2.");var prodWWW2MetricsHostDomains = new Array("www2.");var prodWWW3MetricsHostDomains = new Array("www3.","papp","pwps","pwas","home.");var prodMetricsHostDomains = new Array("www.","ira.","rollover.","metrics.","individual.","corporate.","rps.");var qualHomeMetricsHostDomains = new Array("home2qual.");var qualWWW2MetricsHostDomains = new Array("www2qual.","pdqual.troweprice.com/rps");var qualWWW3MetricsHostDomains = new Array("www3qual.","qeecm","qwps","qwas","pdqual","peecm");var qualMetricsHostDomains = new Array("metricsqual.","corporatequal.","rpsqual.");var devHomeMetricsHostDomains = new Array("home2dev.");var devWWW2MetricsHostDomains = new Array("www2dev.","pddev.troweprice.com/rps");var devWWW3MetricsHostDomains = new Array("www3dev.","deecm","dapp","dwps","dwas","pddev");var devMetricsHostDomains = new Array("metricsdev.","localhost","h30924","h31978","corporatedev.","rpsdev");var prodHomeMetricsServer = "//home2.troweprice.com/metrics";var prodWWW2MetricsServer = "//www2.troweprice.com/metrics";var prodWWW3MetricsServer = "//www3.troweprice.com/metrics";var prodMetricsServer = "//metrics.troweprice.com";var qualHomeMetricsServer = "//home2qual.troweprice.com/metrics";var qualWWW2MetricsServer = "//www2qual.troweprice.com/metrics";var qualWWW3MetricsServer = "//www3qual.troweprice.com/metrics";var qualMetricsServer = "//metricsqual.troweprice.com";var devHomeMetricsServer = "//home2dev.troweprice.com/metrics";var devWWW2MetricsServer = "//www2dev.troweprice.com/metrics";var devWWW3MetricsServer = "//www3dev.troweprice.com/metrics";var devMetricsServer = "//metricsdev.troweprice.com";var metricsServer = "//metrics.troweprice.com";var trackingResource = "/trpwa_i.txt";var logFlag = "Log=1";var isIE  = (navigator.appVersion.indexOf("MSIE") != -1) ? true : false;var isWin = (navigator.appVersion.toLowerCase().indexOf("win") != -1) ? true : false;var isOpera = (navigator.userAgent.indexOf("Opera") != -1) ? true : false;
function removeHTMLTags(htmlString){if(htmlString){var mydiv = document.createElement("div");mydiv.innerHTML = htmlString;if (document.all){return mydiv.innerText;}else {return mydiv.textContent;}}}
function getMetricsServer(){var x;var hostname = window.location.hostname;for ( x in prodHomeMetricsHostDomains ) {if (hostname.indexOf(prodHomeMetricsHostDomains[x]) != -1){metricsServer = prodHomeMetricsServer;return;}}x=0;for ( x in prodWWW3MetricsHostDomains ) {if (hostname.indexOf(prodWWW3MetricsHostDomains[x]) != -1){metricsServer = prodWWW3MetricsServer;return;}}x=0;for ( x in prodWWW2MetricsHostDomains ) {if (hostname.indexOf(prodWWW2MetricsHostDomains[x]) != -1){metricsServer = prodWWW2MetricsServer;return;}}x=0;for ( x in prodMetricsHostDomains ) {if (hostname.indexOf(prodMetricsHostDomains[x]) != -1){metricsServer = prodMetricsServer;return;}}x=0;for ( x in qualHomeMetricsHostDomains ) {if (hostname.indexOf(qualHomeMetricsHostDomains[x]) != -1){metricsServer = qualHomeMetricsServer;return;}}x=0;for ( x in qualWWW3MetricsHostDomains ) {if (hostname.indexOf(qualWWW3MetricsHostDomains[x]) != -1){metricsServer = qualWWW3MetricsServer;return;}}x=0;for ( x in qualWWW2MetricsHostDomains ) {if (hostname.indexOf(qualWWW2MetricsHostDomains[x]) != -1){metricsServer = qualWWW2MetricsServer;return;}}x=0;for ( x in qualMetricsHostDomains ) {if (hostname.indexOf(qualMetricsHostDomains[x]) != -1){metricsServer = qualMetricsServer;return;}}x=0;for ( x in devHomeMetricsHostDomains ) {if (hostname.indexOf(devHomeMetricsHostDomains[x]) != -1){metricsServer = devHomeMetricsServer;return;}}x=0;for ( x in devWWW3MetricsHostDomains ) {if (hostname.indexOf(devWWW3MetricsHostDomains[x]) != -1){metricsServer = devWWW3MetricsServer;return;}}x=0;for ( x in devWWW2MetricsHostDomains ) {if (hostname.indexOf(devWWW2MetricsHostDomains[x]) != -1){metricsServer = devWWW2MetricsServer;return;}}x=0;for ( x in devMetricsHostDomains ) {if (hostname.indexOf(devMetricsHostDomains[x]) != -1){metricsServer = devMetricsServer;return;}}}
function ControlVersion(){var version;var axo;var e;try {axo = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7");version = axo.GetVariable("$version");} catch (e) {}if (!version){try {axo = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");version = "WIN 6,0,21,0";axo.AllowScriptAccess = "always";version = axo.GetVariable("$version");} catch (e) {}}if (!version){try {axo = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");version = axo.GetVariable("$version");} catch (e) {}}if (!version){try {axo = new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3");version = "WIN 3,0,18,0";} catch (e) {}}if (!version){try {axo = new ActiveXObject("ShockwaveFlash.ShockwaveFlash");version = "WIN 2,0,0,11";} catch (e) {version = -1;}}return version;}
function GetSwfVer(){var flashVer = -1;if (navigator.plugins != null && navigator.plugins.length > 0) {if (navigator.plugins["Shockwave Flash 2.0"] || navigator.plugins["Shockwave Flash"]) {var swVer2 = navigator.plugins["Shockwave Flash 2.0"] ? " 2.0" : "";var flashDescription = navigator.plugins["Shockwave Flash" + swVer2].description;var descArray = flashDescription.split(" ");var tempArrayMajor = descArray[2].split(".");			var versionMajor = tempArrayMajor[0];var versionMinor = tempArrayMajor[1];var versionRevision = descArray[3];if (versionRevision == "") {versionRevision = descArray[4];}if (versionRevision[0] == "d") {versionRevision = versionRevision.substring(1);} else if (versionRevision[0] == "r") {versionRevision = versionRevision.substring(1);if (versionRevision.indexOf("d") > 0) {versionRevision = versionRevision.substring(0, versionRevision.indexOf("d"));}}var flashVer = versionMajor + "." + versionMinor + "." + versionRevision;}}else if (navigator.userAgent.toLowerCase().indexOf("webtv/2.6") != -1) flashVer = 4;else if (navigator.userAgent.toLowerCase().indexOf("webtv/2.5") != -1) flashVer = 3;else if (navigator.userAgent.toLowerCase().indexOf("webtv") != -1) flashVer = 2;else if ( isIE && isWin && !isOpera ) {flashVer = ControlVersion();}return flashVer;}
function getEnv(){var hostname = window.location.hostname;if (hostname.indexOf("peecm") != -1){env = "stage";return;}}
getEnv();
if (!WTA) WTA = {};
WTA.globalNamespace = this;
WTA.createNamespace = function(name){if (name.charAt(0) != '.' && name.charAt(name.length-1) != '.' && name.indexOf("..") == -1){var parts = name.split('.');var container = WTA.globalNamespace;var names = "";for (var i=0; i < parts.length; i++){var part = parts[i];names = names + part;if (part.substring(0,1) != part.substring(0,1).toUpperCase() || part == 'WTA'){ if (!container[part])container[part] = {};container = container[part];if (!container.NAME) container.NAME = names;if (i < parts.length -1) names = names + '.';}}var namespace = container;return namespace;}};
WTA.createNamespace('WTA.utils');
WTA.utils.tags ={
data_count:0,
initialize:function(){if (typeof v != "undefined"){v["v_pn"]=document.URL;v["v_site"]="RPS";v["v_event"]="LD";}data_count=0;},
initializespon:function(){if (typeof v != "undefined"){v["v_pn"]=document.URL;v["v_site"]="SPON";v["v_event"]="LD";}data_count=0;},
initializepartic:function(){if (typeof v != "undefined"){v["v_pn"]=document.URL;v["v_site"]="PARTIC";v["v_event"]="LD";}data_count=0;},
initializemc:function(site){if (typeof v != "undefined"){v["v_pn"]=document.URL;if (site != "undefined"){v["v_site"]=site;}else{v["v_site"]="MICROSITE";}v["v_event"]="LD";}data_count=0;},
initializesite:function(site){if (typeof v != "undefined"){v["v_pn"]=document.URL;if (site != "undefined"){v["v_site"]=site;}else{v["v_site"]="UNDEFINED";}v["v_event"]="LD";}data_count=0;},
initializeretail:function(){if (typeof v != "undefined"){v["v_pn"]=document.URL;v["v_site"]="RETAIL";v["v_event"]="LD";}data_count=0;},
initializepnretail:function(pn){if (typeof v != "undefined"){v={};if (pn != "undefined"){v["v_pn"]=pn;}else{v["v_pn"]=document.URL;}v["v_site"]="RETAIL";v["v_event"]="LD";}data_count=0;},
initializepntpd:function(pn){if (typeof v != "undefined"){v={};if (pn != "undefined"){v["v_pn"]=pn;}else{v["v_pn"]=document.URL;}v["v_site"]="TPD";v["v_event"]="LD";}data_count=0;},
initializeexchg:function(){if (typeof v != "undefined"){v["v_pn"]=document.URL;v["v_site"]="EXCHG";v["v_event"]="LD";}data_count=0;},
initializeiws:function(){if (typeof v != "undefined"){v["v_pn"]=document.URL;v["v_site"]="IWS";v["v_event"]="LD";}data_count=0;},
addtemplate:function(template){if (typeof v != "undefined"){v["v_template"]=template;}},
addComponent:function(component,placement,comp_type){if (typeof v != "undefined"){if (data_count == 0){v["v_page_data"] = "v_comp=" + component + "|" + "v_plmt=" + placement + "|" + "v_comp_type=" + comp_type;}else{v["v_page_data"] += "~" + "v_comp=" + component + "|" + "v_plmt=" + placement + "|" + "v_comp_type=" + comp_type;}data_count++;}},
addPageData:function(data){if (typeof v != "undefined"){if (data_count == 0){v["v_page_data"] = data;}else{v["v_page_data"] += "~" + data;}data_count++;}},
addLinkData:function(data){if (typeof v != "undefined"){v["v_link_data"] = data;}},
flush2:function(){var now = new Date();var metricServer = getMetricsServer();var swfVersion =GetSwfVer();var d = {};d["dr"] = document.referrer;d["du"] = document.URL;v["v_fv"]=GetSwfVer();if (env != ""){v["v_env"]=env;}var vo = "";for ( dKey in d ) {vo = vo+"&"+dKey+"="+escape(d[dKey]);}if (typeof v != "undefined") {for ( vKey in v ) {vo = vo+"&"+vKey+"="+escape(v[vKey]);}}var url1 = metricsServer+trackingResource+"?" + logFlag + "&" + vo + "&cb=" + now.getTime();var script_id = null;var script = document.createElement('script');script.setAttribute('type', 'text/javascript');script.setAttribute('src', url1);script.setAttribute('id', 'script_id');script_id = document.getElementById('script_id');if(script_id){document.getElementsByTagName('head')[0].removeChild(script_id);}document.getElementsByTagName('head')[0].appendChild(script);},
flush:function(){var now = new Date();getMetricsServer();var ct = "<img src=";var cd = metricsServer; var cu = trackingResource+"?"+logFlag; var ce = " border=0 height=1 width=1>";var c = {};c["cb"] = now.getTime();var co = "";for ( cKey in c ) {co = co+"&"+cKey+"="+escape(c[cKey]);}var d = {};d["dr"] = document.referrer;d["du"] = document.URL;v["v_fv"]=GetSwfVer();if (env != ""){v["v_env"]=env;}var vo = "";for ( dKey in d ) {vo = vo+"&"+dKey+"="+escape(d[dKey]);}if (typeof v != "undefined") {for ( vKey in v ) {vo = vo+"&"+vKey+"="+escape(v[vKey]);}}document.write(ct,cd,cu,vo,co,ce);},
sendretaillink:function(component,linktext){WTA.utils.tags.sendlinktag(component,linktext,"RETAIL");},
sendexchglink:function(component,linktext,pagedata){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var queryparam = "v_site=EXCHG&v_event=CLK&v_comp=" + escape(component) + "&v_link=" + escape(linktext) + "&v_edu=" + escape(document.URL) + "&v_page_data=" + escape(pagedata);WTA.utils.tags.send(queryparam);},
sendlinktag:function(component,linktext,site){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var queryparam = "v_site=" + site + "&v_event=CLK&v_comp=" + escape(component) + "&v_link=" + escape(linktext) + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
sendretaillinkp:function(component,linktext,linkplmt){return WTA.utils.tags.sendlinkptag(component,linktext,linkplmt,"RETAIL");},
sendexchglinkp:function(component,linktext,linkplmt,pagedata){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var queryparam = "v_site=EXCHG&v_event=CLK&v_comp=" + escape(component) + "&v_link=" + escape(linktext) + "&v_linkplmt=" + (linkplmt) + "&v_edu=" + escape(document.URL) + "&v_page_data=" + escape(pagedata);return WTA.utils.tags.send(queryparam);},
sendlinkptag:function(component,linktext,linkplmt,site){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var queryparam = "v_site=" + site + "&v_event=CLK&v_comp=" + escape(component) + "&v_link=" + escape(linktext) + "&v_linkplmt=" + (linkplmt) + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
sendretailclickp:function(component,query){return WTA.utils.tags.sendclickptag(component,query,"RETAIL");},
sendclickptag:function(component,query,site){if (query != ""){query = "&" + query;}var queryparam = "v_site=" + site + "&v_event=CLK&v_comp=" + escape(component) + query + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
sendretailexitjs:function(element,component,linktext,linkplmt){return WTA.utils.tags.sendexitjstag(element,component,linktext,linkplmt,"RETAIL");},
sendexchgexitjs:function(element,component,linktext,linkplmt,pagedata){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var extlnkref = "";if (typeof element != undefined){if (typeof element.href != "undefined"){extlnkref = element.href;}else{extlnkref = element;}}var queryparam = "v_site=EXCHG&v_event=EXTCLK&v_comp=" + escape(component) + "&v_link=" + escape(linktext) + "&v_linkplmt=" + (linkplmt) + "&v_edu=" + escape(document.URL) + "&v_extlnk=" + escape(extlnkref) + "&v_page_data=" + escape(pagedata);WTA.utils.tags.send(queryparam);},
sendcorpexitjs:function(element,component,linktext,linkplmt){return WTA.utils.tags.sendexitjstag(element,component,linktext,linkplmt,"CORP");},
sendcarexitjs:function(element,component,linktext,linkplmt){return WTA.utils.tags.sendexitjstag(element,component,linktext,linkplmt,"CAR");},
sendtpdexitjs:function(element,component,linktext,linkplmt){return WTA.utils.tags.sendexitjstag(element,component,linktext,linkplmt,"TPD");},
sendexitjstag:function(element,component,linktext,linkplmt,site){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var extlnkref = "";if (typeof element != undefined){if (typeof element.href != "undefined"){extlnkref = element.href;}else{extlnkref = element;}}var queryparam = "v_site=" + site + "&v_event=EXTCLK&v_comp=" + escape(component) + "&v_link=" + escape(linktext) + "&v_linkplmt=" + (linkplmt) + "&v_edu=" + escape(document.URL) + "&v_extlnk=" + escape(extlnkref);WTA.utils.tags.send(queryparam);},
sendretailexiturl:function(element,component,linktext,linkplmt){return WTA.utils.tags.sendexiturltag(element,component,linktext,linkplmt,"RETAIL");},
sendexchgexiturl:function(element,component,linktext,linkplmt,pagedata){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var extlnkref = "";if (typeof element != undefined){if (typeof element.href != "undefined"){extlnkref = element.href;}else{extlnkref = element;}}var queryparam = "v_site=EXCHG&v_event=EXTCLK&v_link=" + escape(linktext) + "&v_comp=" + escape(component) + "&v_linkplmt=" + escape(linkplmt) + "&v_edu=" + escape(document.URL) + "&v_extlnk=" + escape(extlnkref) + "&v_page_data=" + escape(pagedata);return WTA.utils.tags.send(queryparam);},
sendcorpexiturl:function(element,component,linktext,linkplmt){return WTA.utils.tags.sendexiturltag(element,component,linktext,linkplmt,"CORP");},
sendcarexiturl:function(element,component,linktext,linkplmt){return WTA.utils.tags.sendexiturltag(element,component,linktext,linkplmt,"CAR");},
senduaexiturl:function(element,component,linktext,linkplmt){return WTA.utils.tags.sendexiturltag2(element,component,linktext,linkplmt,"UA");},
sendtpdexiturl:function(element,component,linktext,linkplmt){return WTA.utils.tags.sendexiturltag(element,component,linktext,linkplmt,"TPD");},
sendexiturltag:function(element,component,linktext,linkplmt,site){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var extlnkref = "";if (typeof element != undefined){if (typeof element.href != "undefined"){extlnkref = element.href;}else{extlnkref = element;}}var queryparam = "v_site=" + site + "&v_event=EXTCLK&v_link=" + escape(linktext) + "&v_comp=" + escape(component) + "&v_linkplmt=" + escape(linkplmt) + "&v_edu=" + escape(document.URL) + "&v_extlnk=" + escape(extlnkref);WTA.utils.tags.send(queryparam);},
sendexiturltag2:function(element,component,linktext,linkplmt,site){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var extlnkref = "";if (typeof element != undefined){if (typeof element.href != "undefined"){extlnkref = element.href;}else{extlnkref = element;}}var queryparam = "v_site=" + site + "&v_event=EXTCLK&v_link=" + escape(linktext) + "&v_comp=" + escape(component) + "&v_linkplmt=" + escape(linkplmt) + "&v_edu=" + escape(document.URL) + "&v_extlnk=" + escape(extlnkref);WTA.utils.tags.send2(queryparam);window.setTimeout(function(){WTA.utils.tags.navigate(element.href);}, 1000);return false;},
sendretailonchange:function(element,component,additionalparam){return WTA.utils.tags.sendonchangetag(element,component,"RETAIL",additionalparam);},
sendexchgonchange:function(element,component,additionalparam){return WTA.utils.tags.sendonchangetag(element,component,"EXCHG",additionalparam);},
sendonchangetag:function(element,component,site,additionalparam){var queryparam = "v_site=" + site + "&v_event=CHNG&v_comp=" + escape(component) + "&v_slctd=" + escape(element.options[element.selectedIndex].value) + "&v_slctd_desc=" + escape(element.options[element.selectedIndex].text);if (typeof additionalparam != "undefined"){queryparam += "&" + additionalparam;}WTA.utils.tags.send(queryparam);},
sendsponlink:function(element,component,linktext){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var queryparam = "v_site=SPON&v_event=CLK&v_comp=" + escape(component) + "&v_link=" + escape(linktext) + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
sendparticlink:function(element,component,linktext){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var queryparam = "v_site=PARTIC&v_event=CLK&v_comp=" + escape(component) + "&v_link=" + escape(linktext) + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
sendmclink:function(element,component,linktext,site){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var queryparam = "v_site="+site+"&v_event=CLK&v_comp=" + escape(component) + "&v_link=" + escape(linktext) + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
sendsponlinkp:function(element,component,linktext,linkplmt){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var queryparam = "v_site=SPON&v_event=CLK&v_comp=" + escape(component) + "&v_link=" + escape(linktext) + "&v_linkplmt=" + escape(linkplmt) + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
sendparticonchange:function(element,component){var queryparam = "v_site=PARTIC&v_event=CHNG&v_comp=" + escape(component) + "&v_slctd=" + escape(element.options[element.selectedIndex].value);WTA.utils.tags.send(queryparam);},
sendmconchange:function(element,component,site){var queryparam = "v_site="+site+"&v_event=CHNG&v_comp=" + escape(component) + "&v_slctd=" + escape(element.options[element.selectedIndex].value);WTA.utils.tags.send(queryparam);},
sendspononchange:function(element,component){var queryparam = "v_site=SPON&v_event=CHNG&v_comp=" + escape(component) + "&v_slctd=" + escape(element.options[element.selectedIndex].value);WTA.utils.tags.send(queryparam);},
sendparticexit:function(element){var queryparam = "v_site=PARTIC&v_event=EXTCLK&v_url=" + escape(element.href) + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
sendmcexit:function(element){var queryparam = "v_site="+site+"&v_event=EXTCLK&v_url=" + escape(element.href) + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
sendsponexit:function(element){var queryparam = "v_site=SPON&v_event=EXTCLK&v_url=" + escape(element.href) + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
sendlink:function(element,component,linktext){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var queryparam = "v_site=RPS&v_event=CLK&v_comp=" + escape(component) + "&v_link=" + escape(linktext) + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
sendlinkp:function(element,component,linktext,linkplmt){if (linktext.indexOf("<") != -1){linktext = removeHTMLTags(linktext);}var queryparam = "v_site=RPS&v_event=CLK&v_comp=" + escape(component) + "&v_link=" + escape(linktext) + "&v_linkplmt=" + escape(linkplmt) + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
sendonchange:function(element,component){var queryparam = "v_site=RPS&v_event=CHNG&v_comp=" + escape(component) + "&v_slctd=" + escape(element.options[element.selectedIndex].value);WTA.utils.tags.send(queryparam);},
sendexit:function(element){var queryparam = "v_site=RPS&v_event=EXTCLK&v_url=" + escape(element.href) + "&v_edu=" + escape(document.URL);WTA.utils.tags.send(queryparam);},
send:function(queryparam){getMetricsServer();if (env != ""){queryparam += "&v_env=" + env;}var now = new Date();var wtatrpImg = document.createElement("img");var src = metricsServer + trackingResource + "?" + logFlag + "&" + queryparam + "&cb="+now.getTime();wtatrpImg.setAttribute("src",src);wtatrpImg.width = wtatrpImg.height = 1;if (dotImgId != 'undefined' && dotImgId != '' && dotImgId != null){document.body.removeChild(dotImgId);}dotImgId = document.body.appendChild(wtatrpImg);},
send2:function(queryparam){getMetricsServer();if (env != ""){queryparam += "&v_env=" + env;}var now = new Date();var src = "http:" + metricsServer + trackingResource + "?" + logFlag + "&" + queryparam + "&cb="+now.getTime();if (document.images){images[index]=new Image();images[index].src=src;index++;}},
sendretailurllink:function(component,linktext){WTA.utils.tags.sendlinkurltag(component,linktext,"RETAIL");},
navigate:function(url){document.location.href = url;}
};